-- SQL aligned with current domain entities (no schema version)
-- Notes:
-- - This variant removes schema usage (identity/catalog/ticketing/public).
-- - Table/column names follow current entity mappings.
-- - InvoiceTicket table is kept in structure as requested.

--------------------------------------------------
-- 1 CINEMA
--------------------------------------------------
CREATE TABLE cinema (
    cinema_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    hotline VARCHAR(20),
    status VARCHAR(20)
);

--------------------------------------------------
-- 2 ROLE
--------------------------------------------------
CREATE TABLE role (
    role_id INTEGER PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL
);

INSERT INTO role (role_id, role_name) VALUES
(1, 'ADMIN'),
(2, 'MANAGER'),
(3, 'STAFF'),
(4, 'CUSTOMER');

--------------------------------------------------
-- 3 USER
--------------------------------------------------
CREATE TABLE "user" (
    user_id UUID PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE,
    birth_date DATE,
    is_active BOOLEAN,
    role_id INTEGER NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    FOREIGN KEY (role_id) REFERENCES role(role_id)
);

--------------------------------------------------
-- 4 EMPLOYEE
--------------------------------------------------
CREATE TABLE employee (
    user_id UUID PRIMARY KEY,
    cinema_id INTEGER,
    hire_date DATE,
    position VARCHAR(100),
    salary DECIMAL(10,2),

    FOREIGN KEY (user_id) REFERENCES "user"(user_id),
    FOREIGN KEY (cinema_id) REFERENCES cinema(cinema_id)
);

--------------------------------------------------
-- 5 CUSTOMER
--------------------------------------------------
CREATE TABLE customer (
    user_id UUID PRIMARY KEY,
    registration_date TIMESTAMP,
    member_level VARCHAR(20),
    loyalty_points INTEGER,

    FOREIGN KEY (user_id) REFERENCES "user"(user_id)
);

--------------------------------------------------
-- 6 ROOM
--------------------------------------------------
CREATE TABLE room (
    room_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cinema_id INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    total_rows INTEGER,
    total_cols INTEGER,
    type VARCHAR(20),

    CONSTRAINT uk_room_cinema_name UNIQUE (cinema_id, name),
    FOREIGN KEY (cinema_id) REFERENCES cinema(cinema_id)
);

--------------------------------------------------
-- 7 SEAT TYPE
--------------------------------------------------
CREATE TABLE seat_type (
    seat_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    price_multiplier DECIMAL(5,2),
    description VARCHAR(255)
);

--------------------------------------------------
-- 8 SEAT
--------------------------------------------------
CREATE TABLE seat (
    seat_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id INTEGER NOT NULL,
    row_label VARCHAR(10),
    seat_number INTEGER,
    grid_row INTEGER,
    grid_col INTEGER,
    seat_type_id INTEGER NOT NULL,
    is_active BOOLEAN,

    CONSTRAINT uk_seat_room_row_number UNIQUE (room_id, row_label, seat_number),
    CONSTRAINT uk_seat_room_grid UNIQUE (room_id, grid_row, grid_col),

    FOREIGN KEY (room_id) REFERENCES room(room_id),
    FOREIGN KEY (seat_type_id) REFERENCES seat_type(seat_type_id)
);

--------------------------------------------------
-- 9 MOVIE
--------------------------------------------------
CREATE TABLE movie (
    movie_id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    director VARCHAR(255),
    duration INTEGER NOT NULL,
    poster_url VARCHAR(255),
    description VARCHAR(255),
    release_date DATE,
    age_rating VARCHAR(10)
);

--------------------------------------------------
-- 10 GENRE
--------------------------------------------------
CREATE TABLE genre (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
);

--------------------------------------------------
-- 11 MOVIE GENRE
--------------------------------------------------
CREATE TABLE movie_genre (
    movie_id UUID,
    genre_id INTEGER,

    PRIMARY KEY (movie_id, genre_id),
    FOREIGN KEY (movie_id) REFERENCES movie(movie_id),
    FOREIGN KEY (genre_id) REFERENCES genre(genre_id)
);

--------------------------------------------------
-- 12 SHOWTIME
--------------------------------------------------
CREATE TABLE showtime (
    showtime_id UUID PRIMARY KEY,
    movie_id UUID,
    room_id INTEGER,

    start_time TIMESTAMP,
    end_time TIMESTAMP,
    base_price DECIMAL(10,2),
    status VARCHAR(20),

    CONSTRAINT uk_showtime_room_start UNIQUE (room_id, start_time),
    FOREIGN KEY (movie_id) REFERENCES movie(movie_id),
    FOREIGN KEY (room_id) REFERENCES room(room_id)
);

--------------------------------------------------
-- 13 BOOKING
--------------------------------------------------
CREATE TABLE booking (
    booking_id UUID PRIMARY KEY,
    user_id UUID,
    showtime_id UUID,

    created_at TIMESTAMP,
    status VARCHAR(20),
    expired_at TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES "user"(user_id),
    FOREIGN KEY (showtime_id) REFERENCES showtime(showtime_id)
);

CREATE INDEX idx_booking_user ON booking(user_id);
CREATE INDEX idx_booking_showtime ON booking(showtime_id);

--------------------------------------------------
-- 15 TICKET
--------------------------------------------------
CREATE TABLE ticket (
    ticket_id UUID PRIMARY KEY,

    booking_id UUID,
    seat_id INTEGER,

    ticket_code VARCHAR(255) UNIQUE,
    price DECIMAL(10,2),
    created_at TIMESTAMP,

    status VARCHAR(20),
    check_in_time TIMESTAMP,

    CONSTRAINT uk_ticket_showtime_seat UNIQUE (booking_id, seat_id),

    FOREIGN KEY (booking_id) REFERENCES booking(booking_id),
    FOREIGN KEY (seat_id) REFERENCES seat(seat_id)
);

CREATE INDEX idx_ticket_seat ON ticket(seat_id);

--------------------------------------------------
-- 16 PRODUCT
--------------------------------------------------
CREATE TABLE product (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(20),
    price DECIMAL(10,2),
    description VARCHAR(255),
    is_active BOOLEAN
);

--------------------------------------------------
-- 17 INVENTORY
--------------------------------------------------
CREATE TABLE inventory (
    inventory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER UNIQUE,
    quantity INTEGER,
    updated_at TIMESTAMP,

    FOREIGN KEY (product_id) REFERENCES product(product_id)
);

--------------------------------------------------
-- 18 PROMOTION
--------------------------------------------------
CREATE TABLE promotion (
    promotion_id UUID PRIMARY KEY,

    code VARCHAR(50) UNIQUE,
    name VARCHAR(255),
    description VARCHAR(255),

    discount_type VARCHAR(20),
    discount_value DECIMAL(10,2),
    max_discount DECIMAL(10,2),

    start_time TIMESTAMP,
    end_time TIMESTAMP,

    usage_limit INTEGER,
    usage_count INTEGER,

    status VARCHAR(20),
    created_at TIMESTAMP
);

--------------------------------------------------
-- 19 PROMOTION CONDITION
--------------------------------------------------
CREATE TABLE promotion_condition (
    condition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    promotion_id UUID,
    condition_type VARCHAR(30),
    condition_value VARCHAR(255),
    created_at TIMESTAMP,

    FOREIGN KEY (promotion_id) REFERENCES promotion(promotion_id)
);

--------------------------------------------------
-- 21 INVOICE
--------------------------------------------------
CREATE TABLE invoice (
    invoice_id UUID PRIMARY KEY,

    customer_id UUID,
    employee_id UUID,
    booking_id UUID,

    created_at TIMESTAMP,

    total_amount DECIMAL(10,2),
    discount_amount DECIMAL(10,2),
    final_amount DECIMAL(10,2),

    payment_method VARCHAR(30),
    payment_transaction_id VARCHAR(255),
    payment_time TIMESTAMP,

    status VARCHAR(20),
    promotion_id UUID,

    FOREIGN KEY (customer_id) REFERENCES "user"(user_id),
    FOREIGN KEY (employee_id) REFERENCES employee(user_id),
    FOREIGN KEY (booking_id) REFERENCES booking(booking_id),
    FOREIGN KEY (promotion_id) REFERENCES promotion(promotion_id)
);

CREATE INDEX idx_invoice_customer ON invoice(customer_id);
CREATE INDEX idx_invoice_booking ON invoice(booking_id);

--------------------------------------------------
-- 22 INVOICE ITEM
--------------------------------------------------
CREATE TABLE invoice_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    invoice_id UUID,
    product_id INTEGER NOT NULL,

    quantity INTEGER,
    unit_price DECIMAL(10,2),

    CONSTRAINT uk_invoice_item_invoice_product UNIQUE (invoice_id, product_id),

    FOREIGN KEY (invoice_id) REFERENCES invoice(invoice_id),
    FOREIGN KEY (product_id) REFERENCES product(product_id)
);

--------------------------------------------------
-- 23 INVOICE TICKET (kept in structure)
--------------------------------------------------
CREATE TABLE InvoiceTicket (
    invoice_id CHAR(36),
    ticket_id CHAR(36),

    PRIMARY KEY(invoice_id, ticket_id),

    FOREIGN KEY (invoice_id) REFERENCES invoice(invoice_id),
    FOREIGN KEY (ticket_id) REFERENCES ticket(ticket_id)
);

CREATE INDEX idx_invoice_ticket_invoice ON InvoiceTicket(invoice_id);
CREATE INDEX idx_invoice_ticket_ticket ON InvoiceTicket(ticket_id);

--------------------------------------------------
-- 20 PROMOTION USAGE
--------------------------------------------------
CREATE TABLE promotion_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    promotion_id UUID,
    user_id UUID,
    invoice_id UUID,

    used_at TIMESTAMP,

    FOREIGN KEY (promotion_id) REFERENCES promotion(promotion_id),
    FOREIGN KEY (user_id) REFERENCES "user"(user_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(invoice_id)
);

